"""Document preprocessing: turn an uploaded resume into LLM-ready inputs.

Output shape:
    {
      "images": list[bytes],   # JPEG/PNG bytes, may be empty
      "text":   str | None,    # extracted plain text, may be None
    }

The vision model accepts the images directly; the optional text is provided
to the model alongside as a hint when available (eg. for DOCX where layout
fidelity matters less than text content).
"""
from __future__ import annotations

import io
from dataclasses import dataclass, field
from pathlib import Path

from PIL import Image

from app.core.exceptions import ValidationError


SUPPORTED_FORMATS = ("pdf", "docx", "png", "jpg", "jpeg")


@dataclass(slots=True)
class PreprocessedDoc:
    images: list[bytes] = field(default_factory=list)
    text: str | None = None


def detect_format(filename: str) -> str:
    ext = Path(filename).suffix.lower().lstrip(".")
    if ext == "jpeg":
        ext = "jpg"
    if ext not in SUPPORTED_FORMATS:
        raise ValidationError(
            f"Unsupported file format: {ext!r}",
            code="VALIDATION_UNSUPPORTED_FORMAT",
            details={"supported": list(SUPPORTED_FORMATS)},
        )
    return ext


def preprocess(filename: str, content: bytes) -> PreprocessedDoc:
    """Dispatch on extension and return normalized inputs."""
    fmt = detect_format(filename)

    if fmt == "pdf":
        return _preprocess_pdf(content)
    if fmt == "docx":
        return _preprocess_docx(content)
    # png / jpg
    return _preprocess_image(content)


# -----------------------------
# PDF
# -----------------------------
def _preprocess_pdf(content: bytes) -> PreprocessedDoc:
    try:
        import fitz
    except ImportError as exc:  # pragma: no cover
        raise RuntimeError("PyMuPDF not installed") from exc

    try:
        doc = fitz.open(stream=content, filetype="pdf")
    except Exception as exc:
        raise ValidationError(
            "Failed to render PDF (file may be corrupt or password-protected)",
            code="VALIDATION_BAD_PDF",
            details={"error": str(exc)[:200]},
        ) from exc

    images: list[bytes] = []
    try:
        # 220 DPI gives ~1820x2570 for A4, making small resume text legible
        # while keeping payload size bounded. PyMuPDF ships wheels for
        # macOS/Windows, so users do not need to install Poppler separately.
        matrix = fitz.Matrix(220 / 72, 220 / 72)
        for page in doc:
            pixmap = page.get_pixmap(matrix=matrix, alpha=False)
            images.append(pixmap.tobytes("png"))
    finally:
        doc.close()
    return PreprocessedDoc(images=images, text=_extract_pdf_text(content))


def _extract_pdf_text(content: bytes) -> str | None:
    """Best-effort extraction of a machine-readable PDF text layer.

    Resumes generated by tools such as wkhtmltopdf often contain a clean text
    layer even when the rendered visual header is small. Passing that text as
    a hint prevents the VLM from relying solely on visual OCR for fragile
    fields like name and phone. Scanned PDFs simply return no text and keep the
    image-only path.
    """
    try:
        import fitz

        doc = fitz.open(stream=content, filetype="pdf")
    except Exception:
        return None

    try:
        text = "\n".join(page.get_text("text", sort=True) for page in doc).strip()
        if not text:
            return None
        return text[:20_000]
    finally:
        doc.close()


# -----------------------------
# DOCX
# -----------------------------
def _preprocess_docx(content: bytes) -> PreprocessedDoc:
    try:
        from docx import Document
    except ImportError as exc:  # pragma: no cover
        raise RuntimeError("python-docx not installed") from exc

    try:
        doc = Document(io.BytesIO(content))
    except Exception as exc:
        raise ValidationError(
            "Failed to parse DOCX",
            code="VALIDATION_BAD_DOCX",
            details={"error": str(exc)[:200]},
        ) from exc

    parts: list[str] = []
    for para in doc.paragraphs:
        text = para.text.strip()
        if text:
            parts.append(text)
    for table in doc.tables:
        for row in table.rows:
            cells = [c.text.strip() for c in row.cells if c.text.strip()]
            if cells:
                parts.append(" | ".join(cells))
    return PreprocessedDoc(images=[], text="\n".join(parts) or None)


# -----------------------------
# Image
# -----------------------------
def _preprocess_image(content: bytes) -> PreprocessedDoc:
    try:
        img = Image.open(io.BytesIO(content))
        img.verify()
    except Exception as exc:
        raise ValidationError(
            "Invalid image file",
            code="VALIDATION_BAD_IMAGE",
            details={"error": str(exc)[:200]},
        ) from exc

    # Re-open since verify() consumes the file pointer.
    img = Image.open(io.BytesIO(content)).convert("RGB")

    # Cap longest edge at 2560 — keeps small Chinese characters readable while
    # bounding token cost. Anything smaller stays as-is.
    longest = max(img.size)
    if longest > 2560:
        scale = 2560 / longest
        new_size = (int(img.size[0] * scale), int(img.size[1] * scale))
        img = img.resize(new_size, Image.LANCZOS)

    # Use PNG so character strokes survive intact; vision models tolerate the
    # larger payload, and resumes are a low-frequency operation per user.
    buf = io.BytesIO()
    img.save(buf, format="PNG", optimize=True)
    return PreprocessedDoc(images=[buf.getvalue()], text=None)
