var MSG = {
  START_FILL: 'START_FILL',
  FILL_PROGRESS: 'FILL_PROGRESS',
  FILL_COMPLETE: 'FILL_COMPLETE',
  FILL_ERROR: 'FILL_ERROR',
  REQUEST_RESUME: 'REQUEST_RESUME',
  REQUEST_RESUME_FILE: 'REQUEST_RESUME_FILE',
  REQUEST_MATCH: 'REQUEST_MATCH',
  RESUME_DATA: 'RESUME_DATA',
  RESUME_FILE_DATA: 'RESUME_FILE_DATA',
  MATCH_RESULT: 'MATCH_RESULT',
  // Page scan + upload feature
  UPLOAD_SCAN: 'UPLOAD_SCAN',
  UPLOAD_SCAN_RESULT: 'UPLOAD_SCAN_RESULT',
  // Cache management
  CLEAR_CACHE: 'CLEAR_CACHE',
};
